name: NeighbourPro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^5.0.2
  marquee: ^2.0.2
  fluttertoast: ^8.2.5
  open_street_map_search_and_pick: ^0.1.1
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter_lints: ^3.0.0
  url_launcher: ^6.0.6
  maps_launcher: ^2.0.1
flutter:
  uses-material-design: true


  